Problem Statement:
We have customers data
We are trying to predict whether or not give a loan

Assets are loan product, and CASA (Current account saving account), Term Deposits (fixed and Recurring). These are with respect to banks.

1. Disbured Amount = Loan amount given to customer
2. OSP = Out Standing Principle (Bakaya)
3. DPD = Days past due (it should be ideally zero)
4. PAR = Portfolio at risk (OSP when DPD > 0)
5. NPA = Non performing asset, (Loan account when DPD > 90 days), Loan that is not defaulted.

Credit Risk types in Banking
1. DPD (zero) : NDA (Non delilnquint account)
2. DPD (0 to 30) : SMA1 (Standard Monitoring Account)
3. DPD (31 to 60) : SMA2 (Standard Monitoring Account)
4. DPD (61 to 90) : SMA3 (Standard Monitoring Account)
5. DPD (90 to 180) : NPA
6. DPD (> 180): Written-Off (Loan which is not present)

NPA Improve = Loan Portfolio quality of the bank will be better = Market sentiment will be good in the stock market.

**NPA types:**  
GNPA = Gross NPA (3-5%) = OSP default  
NNPA = Net NPA = (0.01 to 0.06%) = Provisioning Amount Subtracted  
Bank quality assess, GNPA

In [4]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
import warnings
import os

In [5]:
# Load the dataset
a1 = pd.read_excel("case_study1.xlsx")
a2 = pd.read_excel("case_study2.xlsx")

df1 = a1.copy()
df2 = a2.copy()

In [6]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

In [7]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [8]:
# Remove nulls
df1 = df1.loc[df1['Age_Oldest_TL'] != -99999]
df1.shape

(51296, 26)

In [9]:
columns_tobe_removed = []

for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 10000:
        columns_tobe_removed.append(i)
        
columns_tobe_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [10]:
df2 = df2.drop(columns_tobe_removed, axis =1)

In [11]:
df2.shape

(51336, 54)

In [12]:
for i in df2.columns:
    df2 = df2.loc[df2[i] != -99999]

In [13]:
df2.shape

(42066, 54)

In [14]:
df2.isna().sum()

PROSPECTID                    0
time_since_recent_payment     0
num_times_delinquent          0
max_recent_level_of_deliq     0
num_deliq_6mts                0
num_deliq_12mts               0
num_deliq_6_12mts             0
num_times_30p_dpd             0
num_times_60p_dpd             0
num_std                       0
num_std_6mts                  0
num_std_12mts                 0
num_sub                       0
num_sub_6mts                  0
num_sub_12mts                 0
num_dbt                       0
num_dbt_6mts                  0
num_dbt_12mts                 0
num_lss                       0
num_lss_6mts                  0
num_lss_12mts                 0
recent_level_of_deliq         0
tot_enq                       0
CC_enq                        0
CC_enq_L6m                    0
CC_enq_L12m                   0
PL_enq                        0
PL_enq_L6m                    0
PL_enq_L12m                   0
time_since_recent_enq         0
enq_L12m                      0
enq_L6m                       0
enq_L3m                       0
MARITALSTATUS                 0
EDUCATION                     0
AGE                           0
GENDER                        0
NETMONTHLYINCOME              0
Time_With_Curr_Empr           0
pct_of_active_TLs_ever        0
pct_opened_TLs_L6m_of_L12m    0
pct_currentBal_all_TL         0
CC_Flag                       0
PL_Flag                       0
pct_PL_enq_L6m_of_L12m        0
pct_CC_enq_L6m_of_L12m        0
pct_PL_enq_L6m_of_ever        0
pct_CC_enq_L6m_of_ever        0
HL_Flag                       0
GL_Flag                       0
last_prod_enq2                0
first_prod_enq2               0
Credit_Score                  0
Approved_Flag                 0
dtype: int64

In [15]:
df1.isna().sum()

PROSPECTID              0
Total_TL                0
Tot_Closed_TL           0
Tot_Active_TL           0
Total_TL_opened_L6M     0
Tot_TL_closed_L6M       0
pct_tl_open_L6M         0
pct_tl_closed_L6M       0
pct_active_tl           0
pct_closed_tl           0
Total_TL_opened_L12M    0
Tot_TL_closed_L12M      0
pct_tl_open_L12M        0
pct_tl_closed_L12M      0
Tot_Missed_Pmnt         0
Auto_TL                 0
CC_TL                   0
Consumer_TL             0
Gold_TL                 0
Home_TL                 0
PL_TL                   0
Secured_TL              0
Unsecured_TL            0
Other_TL                0
Age_Oldest_TL           0
Age_Newest_TL           0
dtype: int64

In [16]:
# Checking common column names
for i in list(df1.columns):
    if i in list(df2.columns):
        print (i)

PROSPECTID

In [17]:
# Merge the two dataframes, inner join so that no nulls are present
df = pd. merge ( df1, df2, how ='inner', left_on = ['PROSPECTID'], right_on = ['PROSPECTID'] )

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROSPECTID                  42064 non-null  int64
 1   Total_TL                    42064 non-null  int64
 2   Tot_Closed_TL               42064 non-null  int64
 3   Tot_Active_TL               42064 non-null  int64
 4   Total_TL_opened_L6M         42064 non-null  int64
 5   Tot_TL_closed_L6M           42064 non-null  int64
 6   pct_tl_open_L6M             42064 non-null  float64
 7   pct_tl_closed_L6M           42064 non-null  float64
 8   pct_active_tl               42064 non-null  float64
 9   pct_closed_tl               42064 non-null  float64
 10  Total_TL_opened_L12M        42064 non-null  int64
 11  Tot_TL_closed_L12M          42064 non-null  int64
 12  pct_tl_open_L12M            42064 non-null  float64
 13  pct_tl_closed_L12M          42064 non-null  float64
 14  Tot_Missed_Pmnt             42064 non-null  int64
 15  Auto_TL                     42064 non-null  int64
 16  CC_TL                       42064 non-null  int64
 17  Consumer_TL                 42064 non-null  int64
 18  Gold_TL                     42064 non-null  int64
 19  Home_TL                     42064 non-null  int64
 20  PL_TL                       42064 non-null  int64
 21  Secured_TL                  42064 non-null  int64
 22  Unsecured_TL                42064 non-null  int64
 23  Other_TL                    42064 non-null  int64
 24  Age_Oldest_TL               42064 non-null  int64
 25  Age_Newest_TL               42064 non-null  int64
 26  time_since_recent_payment   42064 non-null  int64
 27  num_times_delinquent        42064 non-null  int64
 28  max_recent_level_of_deliq   42064 non-null  int64
 29  num_deliq_6mts              42064 non-null  int64
 30  num_deliq_12mts             42064 non-null  int64
 31  num_deliq_6_12mts           42064 non-null  int64
 32  num_times_30p_dpd           42064 non-null  int64
 33  num_times_60p_dpd           42064 non-null  int64
 34  num_std                     42064 non-null  int64
 35  num_std_6mts                42064 non-null  int64
 36  num_std_12mts               42064 non-null  int64
 37  num_sub                     42064 non-null  int64
 38  num_sub_6mts                42064 non-null  int64
 39  num_sub_12mts               42064 non-null  int64
 40  num_dbt                     42064 non-null  int64
 41  num_dbt_6mts                42064 non-null  int64
 42  num_dbt_12mts               42064 non-null  int64
 43  num_lss                     42064 non-null  int64
 44  num_lss_6mts                42064 non-null  int64
 45  num_lss_12mts               42064 non-null  int64
 46  recent_level_of_deliq       42064 non-null  int64
 47  tot_enq                     42064 non-null  int64
 48  CC_enq                      42064 non-null  int64
 49  CC_enq_L6m                  42064 non-null  int64
 50  CC_enq_L12m                 42064 non-null  int64
 51  PL_enq                      42064 non-null  int64
 52  PL_enq_L6m                  42064 non-null  int64
 53  PL_enq_L12m                 42064 non-null  int64
 54  time_since_recent_enq       42064 non-null  int64
 55  enq_L12m                    42064 non-null  int64
 56  enq_L6m                     42064 non-null  int64
 57  enq_L3m                     42064 non-null  int64
 58  MARITALSTATUS               42064 non-null  object
 59  EDUCATION                   42064 non-null  object
 60  AGE                         42064 non-null  int64
 61  GENDER                      42064 non-null  object
 62  NETMONTHLYINCOME            42064 non-null  int64
 63  Time_With_Curr_Empr         42064 non-null  int64
 64  pct_of_active_TLs_ever      42064 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m  42064 non-null  float64
 66  pct_currentBal_all_TL       42064 non-null  float64
 67  CC_Flag                     42064 non-null  int64
 68  PL_Flag                     42064 non-null  int64
 69  pct_PL_enq_L6m_of_L12m      42064 non-null  float64
 70  pct_CC_enq_L6m_of_L12m      42064 non-null  float64
 71  pct_PL_enq_L6m_of_ever      42064 non-null  float64
 72  pct_CC_enq_L6m_of_ever      42064 non-null  float64
 73  HL_Flag                     42064 non-null  int64
 74  GL_Flag                     42064 non-null  int64
 75  last_prod_enq2              42064 non-null  object
 76  first_prod_enq2             42064 non-null  object
 77  Credit_Score                42064 non-null  int64
 78  Approved_Flag               42064 non-null  object
dtypes: float64(13), int64(60), object(6)
memory usage: 25.4+ MB

We will divide the dataset as a numerical and categorical.

In [19]:
# check how many columns are categorical
for i in df.columns:
    if df[i].dtype == 'object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [20]:
df['GENDER'].value_counts()
df['Approved_Flag'].value_counts()

Approved_Flag
P2    25452
P3     6440
P4     5264
P1     4908
Name: count, dtype: int64

Checking they are associated, not with label encoding

In [21]:
# Chi-square test (Consistency table)
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, _, _ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287

Since all the categorical features have p-value less than 0.05, we will accept all

In [22]:
# VIF for numerical columns
numeric_columns = []
for i in df.columns:
    if df[i].dtype != 'object' and i not in ['PROSPECTID','Approved_Flag']:
        numeric_columns.append(i)
        
        
# VIF sequentially check

vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0


        
for i in range (0,total_columns):
    
    vif_value = variance_inflation_factor(vif_data, column_index)
    print (column_index,'---',vif_value)
    
    
    if vif_value <= 6:
        columns_to_be_kept.append( numeric_columns[i] )
        column_index = column_index+1
    
    else:
        vif_data = vif_data.drop([ numeric_columns[i] ] , axis=1)

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000336
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.8328007921530785
3 --- 6.099653381646739
3 --- 5.5813520096427585
4 --- 1.985584353098778

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.809538302819343
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.384346405965583
7 --- 3.0646584155234247
8 --- 2.898639771299253
9 --- 4.377876915347322
10 --- 2.207853583695844
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721434

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427232
15 --- 1.4210050015175733
16 --- 8.083255010190316
16 --- 1.6241227524040114
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.825857047132431
18 --- 1.5080839450032666
19 --- 2.172088834824577
20 --- 2.6233975535272283
21 --- 2.2959970812106167
22 --- 7.360578319196439
22 --- 2.1602387773102554
23 --- 2.8686288267891467
24 --- 6.458218003637272
24 --- 2.8474118865638256
25 --- 4.753198156284083
26 --- 16.22735475594825
26 --- 6.424377256363877
26 --- 8.887080381808687
26 --- 2.3804746142952653
27 --- 8.609513476514548
27 --- 13.06755093547673
27 --- 3.500040056654654
28 --- 1.908795587481377
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.104855915136433
30 --- 2.7971639638512915
31 --- 3.424171203217696
32 --- 10.175021454450935
32 --- 6.408710354561301
32 --- 1.0011511962625614
33 --- 3.069197305397274
34 --- 2.8091261600643715
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.8331649740532163
36 --- 1.568083990954204
37 --- 1.9307572353811677
38 --- 4.331265056645247
39 --- 9.390334396150173

In [23]:
# check Anova for columns_to_be_kept 

from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])  
    b = list(df['Approved_Flag'])  
    
    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)
        

# feature selection is done for cat and num features

In [24]:
# Chisquare Test
# Whenver you're trying to understand a concept, please take very easy examples

#If there is no connection between the variables then p > 0.05.

In [25]:
# listing all the final features
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [26]:
# Label encoding for the categorical features
['MARITALSTATUS', 'EDUCATION', 'GENDER' , 'last_prod_enq2' ,'first_prod_enq2']

print(df['MARITALSTATUS'].unique())    
print(df['EDUCATION'].unique())
print(df['GENDER'].unique())
print(df['last_prod_enq2'].unique())
df['first_prod_enq2'].unique()

['Married' 'Single']
['12TH' 'GRADUATE' 'SSC' 'POST-GRADUATE' 'UNDER GRADUATE' 'OTHERS'
 'PROFESSIONAL']
['M' 'F']
['PL' 'ConsumerLoan' 'AL' 'CC' 'others' 'HL']

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [27]:
# Ordinal feature -- EDUCATION
# SSC            : 1
# 12TH           : 2
# GRADUATE       : 3
# UNDER GRADUATE : 3
# POST-GRADUATE  : 4
# OTHERS         : 1 (It has to be verfied by the business and user)
# PROFESSIONAL   : 3



# Others has to be verified by the business end user 




df.loc[df['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
df.loc[df['EDUCATION'] == '12TH',['EDUCATION']]             = 2
df.loc[df['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
df.loc[df['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
df.loc[df['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
df.loc[df['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
df.loc[df['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

In [28]:
print(df['EDUCATION'].value_counts())
df['EDUCATION'] = df['EDUCATION'].astype(int)
df.info()

EDUCATION
3    18931
2    11703
1     9532
4     1898
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   pct_tl_open_L6M            42064 non-null  float64
 1   pct_tl_closed_L6M          42064 non-null  float64
 2   Tot_TL_closed_L12M         42064 non-null  int64
 3   pct_tl_closed_L12M         42064 non-null  float64
 4   Tot_Missed_Pmnt            42064 non-null  int64
 5   CC_TL                      42064 non-null  int64
 6   Home_TL                    42064 non-null  int64
 7   PL_TL                      42064 non-null  int64
 8   Secured_TL                 42064 non-null  int64
 9   Unsecured_TL               42064 non-null  int64
 10  Other_TL                   42064 non-null  int64
 11  Age_Oldest_TL              42064 non-null  int64
 12  Age_Newest_TL              42064 non-null  int64
 13  time_since_recent_payment  42064 non-null  int64
 14  max_recent_level_of_deliq  42064 non-null  int64
 15  num_deliq_6_12mts          42064 non-null  int64
 16  num_times_60p_dpd          42064 non-null  int64
 17  num_std_12mts              42064 non-null  int64
 18  num_sub                    42064 non-null  int64
 19  num_sub_6mts               42064 non-null  int64
 20  num_sub_12mts              42064 non-null  int64
 21  num_dbt                    42064 non-null  int64
 22  num_dbt_12mts              42064 non-null  int64
 23  num_lss                    42064 non-null  int64
 24  recent_level_of_deliq      42064 non-null  int64
 25  CC_enq_L12m                42064 non-null  int64
 26  PL_enq_L12m                42064 non-null  int64
 27  time_since_recent_enq      42064 non-null  int64
 28  enq_L3m                    42064 non-null  int64
 29  NETMONTHLYINCOME           42064 non-null  int64
 30  Time_With_Curr_Empr        42064 non-null  int64
 31  CC_Flag                    42064 non-null  int64
 32  PL_Flag                    42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever     42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever     42064 non-null  float64
 35  HL_Flag                    42064 non-null  int64
 36  GL_Flag                    42064 non-null  int64
 37  MARITALSTATUS              42064 non-null  object
 38  EDUCATION                  42064 non-null  int64
 39  GENDER                     42064 non-null  object
 40  last_prod_enq2             42064 non-null  object
 41  first_prod_enq2            42064 non-null  object
 42  Approved_Flag              42064 non-null  object
dtypes: float64(5), int64(33), object(5)
memory usage: 13.8+ MB

In [29]:
df_encoded = pd.get_dummies(df, columns=['MARITALSTATUS','GENDER', 'last_prod_enq2' ,'first_prod_enq2'])
df_encoded.info()
k = df_encoded.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 55 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               42064 non-null  float64
 1   pct_tl_closed_L6M             42064 non-null  float64
 2   Tot_TL_closed_L12M            42064 non-null  int64
 3   pct_tl_closed_L12M            42064 non-null  float64
 4   Tot_Missed_Pmnt               42064 non-null  int64
 5   CC_TL                         42064 non-null  int64
 6   Home_TL                       42064 non-null  int64
 7   PL_TL                         42064 non-null  int64
 8   Secured_TL                    42064 non-null  int64
 9   Unsecured_TL                  42064 non-null  int64
 10  Other_TL                      42064 non-null  int64
 11  Age_Oldest_TL                 42064 non-null  int64
 12  Age_Newest_TL                 42064 non-null  int64
 13  time_since_recent_payment     42064 non-null  int64
 14  max_recent_level_of_deliq     42064 non-null  int64
 15  num_deliq_6_12mts             42064 non-null  int64
 16  num_times_60p_dpd             42064 non-null  int64
 17  num_std_12mts                 42064 non-null  int64
 18  num_sub                       42064 non-null  int64
 19  num_sub_6mts                  42064 non-null  int64
 20  num_sub_12mts                 42064 non-null  int64
 21  num_dbt                       42064 non-null  int64
 22  num_dbt_12mts                 42064 non-null  int64
 23  num_lss                       42064 non-null  int64
 24  recent_level_of_deliq         42064 non-null  int64
 25  CC_enq_L12m                   42064 non-null  int64
 26  PL_enq_L12m                   42064 non-null  int64
 27  time_since_recent_enq         42064 non-null  int64
 28  enq_L3m                       42064 non-null  int64
 29  NETMONTHLYINCOME              42064 non-null  int64
 30  Time_With_Curr_Empr           42064 non-null  int64
 31  CC_Flag                       42064 non-null  int64
 32  PL_Flag                       42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever        42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever        42064 non-null  float64
 35  HL_Flag                       42064 non-null  int64
 36  GL_Flag                       42064 non-null  int64
 37  EDUCATION                     42064 non-null  int64
 38  Approved_Flag                 42064 non-null  object
 39  MARITALSTATUS_Married         42064 non-null  bool
 40  MARITALSTATUS_Single          42064 non-null  bool
 41  GENDER_F                      42064 non-null  bool
 42  GENDER_M                      42064 non-null  bool
 43  last_prod_enq2_AL             42064 non-null  bool
 44  last_prod_enq2_CC             42064 non-null  bool
 45  last_prod_enq2_ConsumerLoan   42064 non-null  bool
 46  last_prod_enq2_HL             42064 non-null  bool
 47  last_prod_enq2_PL             42064 non-null  bool
 48  last_prod_enq2_others         42064 non-null  bool
 49  first_prod_enq2_AL            42064 non-null  bool
 50  first_prod_enq2_CC            42064 non-null  bool
 51  first_prod_enq2_ConsumerLoan  42064 non-null  bool
 52  first_prod_enq2_HL            42064 non-null  bool
 53  first_prod_enq2_PL            42064 non-null  bool
 54  first_prod_enq2_others        42064 non-null  bool
dtypes: bool(16), float64(5), int64(33), object(1)
memory usage: 13.2+ MB

Machine Learing model fitting (Data Processing)

In [30]:
# 1. Random Forest

y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier(n_estimators = 200, random_state=42)
rf_classifier.fit(x_train, y_train)


y_pred = rf_classifier.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy}')
print ()
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)


for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}") # F1 score = 2 * p * r / (P + r)
    print()

Accuracy: 0.7636990372043266

Class p1:
Precision: 0.8370457209847597
Recall: 0.7041420118343196
F1 Score: 0.7648634172469202

Class p2:
Precision: 0.7957519116397621
Recall: 0.9282457879088206
F1 Score: 0.856907593778591

Class p3:
Precision: 0.4423380726698262
Recall: 0.21132075471698114
F1 Score: 0.28600612870275793

Class p4:
Precision: 0.7178502879078695
Recall: 0.7269193391642371
F1 Score: 0.7223563495895703

In [31]:
# 2. xgboost

import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4)
y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=10)
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 1.00

Class p1:
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Class p2:
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Class p3:
Precision: 1.0
Recall: 0.9991889699918897
F1 Score: 0.9995943204868154

Class p4:
Precision: 0.9990662931839402
Recall: 1.0
F1 Score: 0.9995329285380663

In [ ]:
df_encoded

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others,first_prod_enq2_AL,first_prod_enq2_CC,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,False,False,True,False,False,False,False,False,True,False
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,True,False,False,False,False,False,True,False,False,False
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,True,False,False,False,False,False,False,False,False,True
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,False,False,False,False,True,False,False,False,False,False
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42061,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,True,False,False,False,False,False,True,False,False,False
42062,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,False,False,False,True,False,False,False,False,False,True
42063,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,True,False,False,False,False,False,False,False,False,True
42064,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,True,False,False,False,False,False,False,False,False,True
42065,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,False,False,False,True,False,False,False,False,False,True

In [ ]:
df_encoded['Approved_Flag'].value_counts()
# By looking at the imbalanced nature of the target variable, we get to decide the loss metrics.

Approved_Flag
P2    25454
P3     6440
P4     5264
P1     4908
Name: count, dtype: int64